### PR TITLE
Document blob-receipt, support username-based restore, remove old receipt-validation, bump to 4.0.0

### PR DESCRIPTION
**Pull request by hansemannn**
Fixing:
- https://github.com/appcelerator-modules/ti.storekit/issues/6
- https://github.com/appcelerator-modules/ti.storekit/issues/16
- https://github.com/appcelerator-modules/ti.storekit/issues/18
- https://github.com/appcelerator-modules/ti.storekit/issues/20
- https://github.com/appcelerator-modules/ti.storekit/issues/21

Also:
- Removing `verifyReceipt` in favor of `validateReceipt`
- Remove pre-iOS 7 code
- Expose `restoreCompletedTransactionsWithApplicationUsername` method
- Update example code

### CODE REVIEW

**Comment by shoniw** [comment]
Hi,
I tested version 3.2.0
and verify receipts on ios 7 still not working, the documents say it has been fixed.
Ran a build in xcode after buiding in Appcelerator.
This is the error:
`[INFO] Restored 6MONTHS
[INFO] Downloads available for restored product
[DEBUG] Transaction finished <SKPaymentTransaction: 0x17400a760>
[ERROR] Script Error {
    column = 4937;
    line = 1;
    message = "Invalid type passed to function";
    nativeLocation = "-[TiStorekitModule verifyReceipt:] (TiStoreKitModule.m:308)";
    nativeReason = "expected: Object, was: TiStorekitTransaction";
    sourceURL = "file:///var/containers/Bundle/Application/E99FD746-4F19-464B-AF90-3CF89F82CC7B/GasBox.app/app.js";
    stack = "[native code]\nfile:///var/containers/Bundle/Application/E99FD746-4F19-464B-AF90-3CF89F82CC7B/GasBox.app/app.js:1:4937";
}`

**Comment by hansemannn** [comment]
@shoniw You used the wrong method and the wrong parameter. Use `var isValid = StoreKit.validateReceipt()` instead.

**Comment by shoniw** [comment]
Hi,
Not sure to what you are refering to as all I did was build the example that is supplied with the module, I have not altered or added any code.
Where would that method be applied.

**Comment by raefa** [comment]
@hansemannn Thanks for keeping this module up-to-date. I think I am experiencing the same issue as @shoniw. `StoreKit.validateReceipt()` is always returning false.

**Comment by hansemannn** [comment]
Thanks guys. Did that work before? Does the rest of this PR work? I plan to spend more time on it after 6.0.3.GA release, but I'd love to have you guys here to continuously test the changes.

**Comment by Astrovic** [comment]
Hi @hansemannn , I have some errors with 3.1.2 version, and with your 3.2.0 version too.
When I try to restore, i receive this log error:
`Failed to restore all completed transactions: Error Domain=SKErrorDomain Code=0 "Cannot connect to iTunes Store" UserInfo={NSLocalizedDescription=Cannot connect to iTunes Store}`

Instead, if I try to buy, I receive this log error:
`Error in transaction: Cannot connect to iTunes Store`
`Transaction finished <SKPaymentTransaction: 0x600000006390>`

**Comment by hansemannn** [comment]
@Astrovic That error is not related to the module, you environment is invalid: 
- http://stackoverflow.com/questions/18891548/skerrordomain-code-0-cannot-connect-to-itunes-store
- https://forums.developer.apple.com/thread/51621

**Comment by hansemannn** [comment]
@raefa I just updated the module to include some more error logs to identify the failure. Please try this version and tell me about the logs occurring, thx!

P.S.: Ensure that this two properties are correctly set, the verification will fail if they are different:
```js
Storekit.bundleVersion = "<YOUR APP BUNDLE VERSION>"; // eg. "1.0.0"
Storekit.bundleIdentifier = "<YOUR APP BUNDLE IDENTIFIER>"; // eg. "com.appc.storekit"
```

[ti.storekit-iphone-3.2.0.zip](https://github.com/appcelerator-archive/ti.storekit/files/922860/ti.storekit-iphone-3.2.0.zip)

**Comment by hansemannn** [comment]
Ok guys, call me crazy but I've just set up a whole In-App environment just to check this. So here is what's going on:
- Ensure to use `validateReceipt`, the other will be removed in this PR
- Ensure you test with a sandbox account when testing in a non-prod environment. Using your regular account will throw an error 100 while refreshing the receipt and resulting in `false` (= not validated). See [this blog](https://samritchie.net/2015/01/29/the-operation-couldnt-be-completed-sserrordomain-error-100/) which really helped me
- Ensure you downloaded the `AppleIncRootCertificate.cer` from Apple and placed in in your app's Resources folder (classic) or app/assets/iphone (Alloy).
- Ensure to you the most recent example/app.js of this PR

**Pull request merged**
